project:
  type: website
  output-dir: docs

website:
  title: "HSMA Project Handbook"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: previous_projects/index.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
