project:
  type: website

website:
  title: "HSMA Project Handbook"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: previous_projects/index.qmd
        text: Projects
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
